services:
  db:
    image: mysql:8.0
    container_name: dexa-mysql
    restart: always
    environment:
      MYSQL_USER: dexa
      MYSQL_PASSWORD: dexa
      MYSQL_ROOT_PASSWORD: dexa
      MYSQL_DATABASE: dexa_db
    ports:
      - '3306:3306'
    volumes:
      - dexa-db-data:/var/lib/mysql
    networks:
      - dexa-network

volumes:
  dexa-db-data:
    name: dexa-db-data
    external: true

networks:
  dexa-network:
    name: dexa-network
